/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 the_dragon_of_rockmine_keep.glb 
Author: Elyutt (https://sketchfab.com/Ludonaut)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-dragon-of-rockmine-keep-00873aef03884f77a3a30853da48d46f
Title: The Dragon of Rockmine Keep
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function DragonRoom(props) {
	const { nodes, materials } = useGLTF(
		'/models/the_dragon_of_rockmine_keep.glb'
	);
	return (
		<group
			{...props}
			dispose={null}
		>
			<group scale={0.1}>
				<mesh
					geometry={nodes.ShelfItems_GEO_ColourChart_MAT_0.geometry}
					material={materials.ColourChart_MAT}
				/>
				<mesh
					geometry={
						nodes.ShelfItems_GEO_PosterAndBooks_MAT_0.geometry
					}
					material={materials.PosterAndBooks_MAT}
				/>
				<mesh
					geometry={nodes.ShelfItems_GEO_GroundTexture_MAT_0.geometry}
					material={materials.GroundTexture_MAT}
				/>
				<mesh
					geometry={nodes.Furniture_GEO_ColourChart_MAT_0.geometry}
					material={materials.ColourChart_MAT}
				/>
				<mesh
					geometry={nodes.Furniture_GEO_SnowAndGlow_MAT_0.geometry}
					material={materials.SnowAndGlow_MAT}
				/>
				<mesh
					geometry={nodes.Furniture_GEO_LampShade_MAT_0.geometry}
					material={materials.LampShade_MAT}
				/>
				<mesh
					geometry={nodes.Furniture_GEO_PosterAndBooks_MAT_0.geometry}
					material={materials.PosterAndBooks_MAT}
				/>
				<mesh
					geometry={nodes.Snow_GEO_SnowAndGlow_MAT_0.geometry}
					material={materials.SnowAndGlow_MAT}
				/>
				<mesh
					geometry={
						nodes.Table_Decorations_GEO_DMPapers_MAT_0.geometry
					}
					material={materials.DMPapers_MAT}
				/>
				<mesh
					geometry={
						nodes.Table_Decorations_GEO_ColourChart_MAT_0.geometry
					}
					material={materials.ColourChart_MAT}
				/>
				<mesh
					geometry={
						nodes.Table_Decorations_GEO_DMScreen_MAT_0.geometry
					}
					material={materials.DMScreen_MAT}
				/>
				<mesh
					geometry={nodes.Table_Decorations_GEO_Glass_MAT_0.geometry}
					material={materials.Glass_MAT}
				/>
				<mesh
					geometry={
						nodes.Table_Decorations_GEO_PlayerSheet_MAT_0.geometry
					}
					material={materials.PlayerSheet_MAT}
				/>
				<mesh
					geometry={
						nodes.Table_Decorations_GEO_GroundTexture_MAT_0.geometry
					}
					material={materials.GroundTexture_MAT}
				/>
				<mesh
					geometry={
						nodes.Table_Decorations_GEO_DragonBlast_MAT_0.geometry
					}
					material={materials.DragonBlast_MAT}
				/>
				<mesh
					geometry={nodes.Room_GEO_ColourChart_MAT_0.geometry}
					material={materials.ColourChart_MAT}
				/>
				<mesh
					geometry={nodes.Room_GEO_GroundTexture_MAT_0.geometry}
					material={materials.GroundTexture_MAT}
				/>
				<mesh
					geometry={nodes.Dragon_GEO_DragonBlast_MAT_0.geometry}
					material={materials.DragonBlast_MAT}
				/>
				<mesh
					geometry={nodes.Dragon_GEO_ColourChart_MAT_0.geometry}
					material={materials.ColourChart_MAT}
				/>
				<mesh
					geometry={nodes.Dragon_GEO_DragonScale_MAT_0.geometry}
					material={materials.DragonScale_MAT}
				/>
				<mesh
					geometry={nodes.RockmineKeep_GEO_Snow_MAT_0.geometry}
					material={materials.Snow_MAT}
				/>
				<mesh
					geometry={nodes.RockmineKeep_GEO_ColourChart_MAT_0.geometry}
					material={materials.ColourChart_MAT}
				/>
				<mesh
					geometry={nodes.RockmineKeep_GEO_DragonBlast_MAT_0.geometry}
					material={materials.DragonBlast_MAT}
				/>
				<mesh
					geometry={
						nodes.RockmineKeep_GEO_GroundTexture_MAT_0.geometry
					}
					material={materials.GroundTexture_MAT}
				/>
				<mesh
					geometry={nodes.RockmineKeep_GEO_SnowAndGlow_MAT_0.geometry}
					material={materials.SnowAndGlow_MAT}
				/>
				<mesh
					geometry={nodes.RockmineKeep_GEO_Water_MAT_0.geometry}
					material={materials.Water_MAT}
				/>
			</group>
		</group>
	);
}

useGLTF.preload('/models/the_dragon_of_rockmine_keep.glb');

