/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 the_magic_room.glb -T 
Files: the_magic_room.glb [827.8KB] > C:\Users\Sakamoto-san\Documents\Code-more\JavaScript Mastery\kristianto-dev\public\models\the_magic_room-transformed.glb [43.89KB] (95%)
Author: thcyrax (https://sketchfab.com/kitsunegraphics)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-magic-room-c7ef79f3c472494db5224d28b8ae417b
Title: The Magic Room
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';

export function MagicRoom(props) {
	const { nodes, materials } = useGLTF(
		'/models/mine/the_magic_room-transformed.glb'
	);
	return (
		<group
			{...props}
			dispose={null}
		>
			<mesh
				geometry={nodes.Circle_Material_0.geometry}
				material={materials.Material}
				position={[41.064, 0, -52.561]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={133.377}
			/>
		</group>
	);
}

useGLTF.preload('/models/mine/the_magic_room-transformed.glb');

