/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hey_good_lookin_-_vinnie.glb 
Author: PaulsRage (https://sketchfab.com/paulsrage)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/hey-good-lookin-vinnie-b88c8c45f3ce454f925db4128f339c5e
Title: Hey Good Lookin' - Vinnie
*/

import React from 'react';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';

export function Vinnie(props) {
	const group = React.useRef();
	const { scene, animations } = useGLTF(
		'/models/hey_good_lookin_-_vinnie.glb'
	);
	const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
	const { nodes, materials } = useGraph(clone);
	const { actions } = useAnimations(animations, group);

	React.useEffect(() => {
		if (actions) {
			// kalau ada banyak animasi, coba mainkan semuanya
			Object.values(actions).forEach((action) => {
				action.reset().fadeIn(0.5).play();
			});
		}
	}, [actions]);

	return (
		<group
			ref={group}
			{...props}
			dispose={null}
		>
			<group name='Sketchfab_Scene'>
				<group
					name='Sketchfab_model'
					rotation={[-Math.PI / 2, 0, 0]}
					scale={0.005}
				>
					<group
						name='6df04177db364fd9a8aae022a3888f38fbx'
						rotation={[Math.PI / 2, 0, 0]}
						scale={0.01}
					>
						<group name='Object_2'>
							<group name='RootNode'>
								<group name='Object_4'>
									<primitive object={nodes._rootJoint} />
									<group name='Object_6' />
									<group name='Object_9' />
									<group name='Object_12' />
									<group name='Object_15' />
									<group name='Object_18' />
									<group name='SM_Trashcan_02'>
										<mesh
											name='SM_Trashcan_02_M_Bck_Elements_Base_0'
											geometry={
												nodes
													.SM_Trashcan_02_M_Bck_Elements_Base_0
													.geometry
											}
											material={
												materials.M_Bck_Elements_Base
											}
										/>
										<mesh
											name='SM_Trashcan_02_M_Outline_0'
											geometry={
												nodes.SM_Trashcan_02_M_Outline_0
													.geometry
											}
											material={materials.M_Outline}
										/>
									</group>
									<group name='SM_Trash'>
										<mesh
											name='SM_Trash_M_Bck_Elements_Base_0'
											geometry={
												nodes
													.SM_Trash_M_Bck_Elements_Base_0
													.geometry
											}
											material={
												materials.M_Bck_Elements_Base
											}
										/>
										<mesh
											name='SM_Trash_M_Outline_0'
											geometry={
												nodes.SM_Trash_M_Outline_0
													.geometry
											}
											material={materials.M_Outline}
										/>
									</group>
									<group name='SM_Bottle_03'>
										<mesh
											name='SM_Bottle_03_M_Bck_Elements_Base_0'
											geometry={
												nodes
													.SM_Bottle_03_M_Bck_Elements_Base_0
													.geometry
											}
											material={
												materials.M_Bck_Elements_Base
											}
										/>
										<mesh
											name='SM_Bottle_03_M_Outline_0'
											geometry={
												nodes.SM_Bottle_03_M_Outline_0
													.geometry
											}
											material={materials.M_Outline}
										/>
									</group>
									<group name='SM_Bottle_01'>
										<mesh
											name='SM_Bottle_01_M_Bck_Elements_Base_0'
											geometry={
												nodes
													.SM_Bottle_01_M_Bck_Elements_Base_0
													.geometry
											}
											material={
												materials.M_Bck_Elements_Base
											}
										/>
										<mesh
											name='SM_Bottle_01_M_Outline_0'
											geometry={
												nodes.SM_Bottle_01_M_Outline_0
													.geometry
											}
											material={materials.M_Outline}
										/>
									</group>
									<group name='SM_Vinnie_Tongue' />
									<group name='SM_Vinnie_Teeth'>
										<group name='SM_Cigarette'>
											<mesh
												name='SM_Cigarette_M_Vinnie_Body_0'
												geometry={
													nodes
														.SM_Cigarette_M_Vinnie_Body_0
														.geometry
												}
												material={
													materials.M_Vinnie_Body
												}
											/>
											<mesh
												name='SM_Cigarette_M_Outline_0'
												geometry={
													nodes
														.SM_Cigarette_M_Outline_0
														.geometry
												}
												material={materials.M_Outline}
											/>
										</group>
									</group>
									<group name='SM_Vinnie_Eye_Right' />
									<group name='SM_Vinnie_Eye_Left' />
									<group name='SM_Vinnie_Body' />
									<group name='SM_Bck'>
										<mesh
											name='SM_Bck_M_Bck_Base_0'
											geometry={
												nodes.SM_Bck_M_Bck_Base_0
													.geometry
											}
											material={materials.M_Bck_Base}
										/>
										<mesh
											name='SM_Bck_M_Outline_0'
											geometry={
												nodes.SM_Bck_M_Outline_0
													.geometry
											}
											material={materials.M_Outline}
										/>
									</group>
									<group name='SM_Newspapper_01'>
										<mesh
											name='SM_Newspapper_01_M_Bck_Elements_Base_0'
											geometry={
												nodes
													.SM_Newspapper_01_M_Bck_Elements_Base_0
													.geometry
											}
											material={
												materials.M_Bck_Elements_Base
											}
										/>
									</group>
									<group name='SM_Newspapper_02'>
										<mesh
											name='SM_Newspapper_02_M_Bck_Elements_Base_0'
											geometry={
												nodes
													.SM_Newspapper_02_M_Bck_Elements_Base_0
													.geometry
											}
											material={
												materials.M_Bck_Elements_Base
											}
										/>
									</group>
									<group name='SM_Flier'>
										<mesh
											name='SM_Flier_M_Bck_Elements_Base_0'
											geometry={
												nodes
													.SM_Flier_M_Bck_Elements_Base_0
													.geometry
											}
											material={
												materials.M_Bck_Elements_Base
											}
										/>
									</group>
									<group name='SM_Bottle_02'>
										<mesh
											name='SM_Bottle_02_M_Bck_Elements_Base_0'
											geometry={
												nodes
													.SM_Bottle_02_M_Bck_Elements_Base_0
													.geometry
											}
											material={
												materials.M_Bck_Elements_Base
											}
										/>
										<mesh
											name='SM_Bottle_02_M_Outline_0'
											geometry={
												nodes.SM_Bottle_02_M_Outline_0
													.geometry
											}
											material={materials.M_Outline}
										/>
									</group>
									<group name='SM_Trashcan_01'>
										<mesh
											name='SM_Trashcan_01_M_Bck_Elements_Base_0'
											geometry={
												nodes
													.SM_Trashcan_01_M_Bck_Elements_Base_0
													.geometry
											}
											material={
												materials.M_Bck_Elements_Base
											}
										/>
										<mesh
											name='SM_Trashcan_01_M_Outline_0'
											geometry={
												nodes.SM_Trashcan_01_M_Outline_0
													.geometry
											}
											material={materials.M_Outline}
										/>
									</group>
									<group name='SM_Trashcan_Lid'>
										<mesh
											name='SM_Trashcan_Lid_M_Bck_Elements_Base_0'
											geometry={
												nodes
													.SM_Trashcan_Lid_M_Bck_Elements_Base_0
													.geometry
											}
											material={
												materials.M_Bck_Elements_Base
											}
										/>
										<mesh
											name='SM_Trashcan_Lid_M_Outline_0'
											geometry={
												nodes
													.SM_Trashcan_Lid_M_Outline_0
													.geometry
											}
											material={materials.M_Outline}
										/>
									</group>
									<group
										name='cam_ui'
										position={[0, -5623.429, 4000]}
										rotation={[0, Math.PI / 2, 0]}
										scale={100}
									>
										<group name='Object_195' />
									</group>
									<skinnedMesh
										name='Object_7'
										geometry={nodes.Object_7.geometry}
										material={materials.M_Vinnie_Body}
										skeleton={nodes.Object_7.skeleton}
									/>
									<skinnedMesh
										name='Object_8'
										geometry={nodes.Object_8.geometry}
										material={materials.M_Outline}
										skeleton={nodes.Object_8.skeleton}
									/>
									<skinnedMesh
										name='Object_10'
										geometry={nodes.Object_10.geometry}
										material={materials.M_Vinnie_Body}
										skeleton={nodes.Object_10.skeleton}
									/>
									<skinnedMesh
										name='Object_11'
										geometry={nodes.Object_11.geometry}
										material={materials.M_Outline}
										skeleton={nodes.Object_11.skeleton}
									/>
									<skinnedMesh
										name='Object_13'
										geometry={nodes.Object_13.geometry}
										material={materials.M_Vinnie_Body}
										skeleton={nodes.Object_13.skeleton}
									/>
									<skinnedMesh
										name='Object_14'
										geometry={nodes.Object_14.geometry}
										material={materials.M_Outline}
										skeleton={nodes.Object_14.skeleton}
									/>
									<skinnedMesh
										name='Object_16'
										geometry={nodes.Object_16.geometry}
										material={materials.M_Vinnie_Body}
										skeleton={nodes.Object_16.skeleton}
									/>
									<skinnedMesh
										name='Object_17'
										geometry={nodes.Object_17.geometry}
										material={materials.M_Outline}
										skeleton={nodes.Object_17.skeleton}
									/>
									<skinnedMesh
										name='Object_19'
										geometry={nodes.Object_19.geometry}
										material={materials.M_Vinnie_Body}
										skeleton={nodes.Object_19.skeleton}
									/>
									<skinnedMesh
										name='Object_20'
										geometry={nodes.Object_20.geometry}
										material={materials.M_Outline}
										skeleton={nodes.Object_20.skeleton}
									/>
								</group>
							</group>
						</group>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/models/hey_good_lookin_-_vinnie.glb');

